services:
  postgres:
    container_name: positions-management-db
    image: postgres:16.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=positions_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
